name: CI Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup JDK 14
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'temurin'
      - run: ant build
      - name: Publish artefacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: bin
          path: bin
      - name: Analysis
        uses: uhafner/quality-monitor@v4.11.0
        with:
          config: >
            {
              "tests": {
                "tools": [
                  {
                    "id": "junit",
                    "name": "Unit tests",
                    "pattern": "bin/tests.json"
                  }
                ]
              }
            } 
