name: CI Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup JDK14 for build
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'temurin'

      - name: Cache
        uses: actions/cache@v5
        id: cache
        with:
          path: .cache
          key: gomodcache

      - name: Build
        run: ant build

      - name: Publish artefacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: bin
          path: bin

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2.18.8
        with:
          profile: ./bin/coverage.txt
          threshold-file: 80
          threshold-package: 80
          threshold-total: 95
